ENV: production
WS_URL: "ws://localhost:8080"
WS_ACCESS_TOKEN: "your_access_token"
GITHUB_WEBHOOK_SECRET: "your_webhook_secret"
GITHUB_REPO:
  - "AptS-1547/AptS-1547"
GITHUB_BRANCH:
  - "main"
QQ_GROUP:
  - 123456789