ENV: production
ONEBOT_URL: ''
ONEBOT_PORTOL_TYPE: 'ws'
ONEBOT_ACCESS_TOKEN: ''
GITHUB_WEBHOOK:
  - NAME: github
    REPO:
      - AptS-1547/onebot-github-webhook
    BRANCH:
      - main
    SECRET: your_secret_here
    EVENTS:
      - push
      - pull_request
      - issues
      - issue_comment
      - release
    ONEBOT:
      - type: group
        id: 123456789