ENV: production
WS_URL: ''
WS_ACCESS_TOKEN: ''
GITHUB_WEBHOOK_SECRET: ''
WEBHOOK:
  - NAME: github
    REPO:
      - AptS-1547/onebot-github-webhook
    BRANCH:
      - main
    EVENTS:
      - push
      - pull_request
      - issues
      - issue_comment
      - release
    ONEBOT:
      - type: group
        id: 123456789
